export const PROJECTS = [
    {
        id: "p1",
        name: "Cloud Sync Engine",
        code: "CSE-014",
        description: "Real-time sync service for cross-device task updates.",
        status: "In Progress",
        progress: 64,
        team: ["AA", "RK", "SS"],
        dueDate: "2025-12-20",
        tasksDone: 18,
        tasksTotal: 24,
        priority: "High",
        tag: "Backend",
    },
    {
        id: "p2",
        name: "Team Workspace UI",
        code: "TW-102",
        description: "New workspace layout with focus & deep work modes.",
        status: "Planning",
        progress: 22,
        team: ["AA", "MG"],
        dueDate: "2026-01-05",
        tasksDone: 4,
        tasksTotal: 18,
        priority: "Medium",
        tag: "Frontend",
    },
    {
        id: "p3",
        name: "Insights & Analytics",
        code: "IA-231",
        description: "Visual dashboards for productivity and team load.",
        status: "Review",
        progress: 87,
        team: ["RK", "SS", "VK", "AA"],
        dueDate: "2025-12-12",
        tasksDone: 33,
        tasksTotal: 38,
        priority: "High",
        tag: "Analytics",
    },
    {
        id: "p4",
        name: "Notification Pipeline",
        code: "NP-088",
        description: "Latency-optimized pipeline for multi-channel alerts.",
        status: "In Progress",
        progress: 45,
        team: ["MG"],
        dueDate: "2025-12-30",
        tasksDone: 9,
        tasksTotal: 20,
        priority: "Low",
        tag: "Infra",
    },
];